plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.botapp'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.botapp"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // WorkManager සහ OkHttp සඳහා අවශ්‍ය ලයිබ්‍රීස්
    implementation 'androidx.work:work-runtime:2.8.1'
    implementation 'com.squareup.okhttp3:okhttp:4.10.0'
}
